apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-6z4n
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-6z4n
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-6z4n
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-6z4n
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-6z4n
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-seyv-tenant/rhtap-demo-app/hacbs-test-project-6z4n@sha256:52254623d7ea1edc2da93504e440947690bd36d98152e05cbe041e9c654437fa
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
